#!/usr/bin/env bash
# Assemble and ad-hoc sign NotificationNanny.app from an already-built binary.
#
# Shared by dev.sh (debug) and build-app.sh (release) so the two cannot drift.
# They did drift: dev.sh copied only Info.plist and AppIcon.icns, so every
# ./scripts/dev.sh bundle silently ran without the menu-bar glyphs (falling back to an
# SF Symbol) and without any localization, while build-app.sh copied both. The
# two scripts still differ in how they *build* — that part is deliberate — but
# from the binary onward they now produce identical bundles.
#
# Usage: scripts/assemble-bundle.sh <binary-path> <app-dir> <version>

set -euo pipefail

BINARY_PATH="${1:?usage: assemble-bundle.sh <binary-path> <app-dir> <version>}"
APP_DIR="${2:?usage: assemble-bundle.sh <binary-path> <app-dir> <version>}"
VERSION="${3:?usage: assemble-bundle.sh <binary-path> <app-dir> <version>}"

APP_NAME="NotificationNanny"
BUNDLE_ID="com.notificationnanny.app"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

CONTENTS="${APP_DIR}/Contents"
MACOS_DIR="${CONTENTS}/MacOS"
RESOURCES_DIR="${CONTENTS}/Resources"

if [[ ! -f "${BINARY_PATH}" ]]; then
    echo "error: built binary not found at ${BINARY_PATH}" >&2
    exit 1
fi

rm -rf "${APP_DIR}"
mkdir -p "${MACOS_DIR}" "${RESOURCES_DIR}"

cp "${BINARY_PATH}" "${MACOS_DIR}/${APP_NAME}"
chmod +x "${MACOS_DIR}/${APP_NAME}"

# Info.plist — substitute the templated keys with real values.
sed \
    -e "s/\$(EXECUTABLE_NAME)/${APP_NAME}/g" \
    -e "s/\$(PRODUCT_BUNDLE_IDENTIFIER)/${BUNDLE_ID}/g" \
    -e "s/\$(MARKETING_VERSION)/${VERSION}/g" \
    "${ROOT}/Resources/Info.plist" > "${CONTENTS}/Info.plist"

# App icon (generated by scripts/generate-icon.swift).
if [[ -f "${ROOT}/Resources/AppIcon.icns" ]]; then
    cp "${ROOT}/Resources/AppIcon.icns" "${RESOURCES_DIR}/AppIcon.icns"
fi

# Menu-bar / UI glyphs (generated by scripts/extract-glyphs.py). Loaded at
# runtime via Bundle.main, so the subdirectory name has to survive the copy.
if [[ -d "${ROOT}/Resources/Glyphs" ]]; then
    cp -R "${ROOT}/Resources/Glyphs" "${RESOURCES_DIR}/"
fi

# Localizations — plain .lproj/Localizable.strings, no Xcode string-catalog
# compiler involved (this project builds with plain SwiftPM). Copied straight
# into Contents/Resources so Bundle.main resolves them the standard way.
for lproj in "${ROOT}"/Resources/*.lproj; do
    [[ -d "${lproj}" ]] || continue
    cp -R "${lproj}" "${RESOURCES_DIR}/"
done

# Ad-hoc codesigning, required for Accessibility TCC to attach to a code identity.
codesign --force --deep --sign - \
    --entitlements "${ROOT}/Resources/NotificationNanny.entitlements" \
    "${APP_DIR}"
